### ISSUE TITLE
Fix incorrect run_mode default values

### ISSUE THREAD

**Issue by engshine** [shinesolutions/puppet-aem-curator#113]
The defaults set for `run_mode` for both author and publish are incorrect.
The `run_mode` variable are meant to be _additional_ runmodes for AEM Author/Publish and not the TYPE (e.g. author, publish).

The default value should be an empty list.

**Comment by cliffano** [comment]
@engshine Is this taken care of by https://github.com/shinesolutions/puppet-aem-curator/commit/c5d644a8f7d5d999dee5baa25a561b3e29963391 ?

**Comment by engshine** [comment]
@cliffano yes, this was the ticket for that issue and fixed in that commit.

**Comment by cliffano** [comment]
Closing this ticket as the change has been made in https://github.com/shinesolutions/puppet-aem-curator/commit/c5d644a8f7d5d999dee5baa25a561b3e29963391 , already included in 1.24.1 .
