### ISSUE TITLE
AEM 6.4 SP 4 Support

### ISSUE THREAD

**Issue by Carnifrex** [shinesolutions/puppet-aem-curator#117]
AEM 6.4 SP4 has been released. We need to add support for aem64_sp4 AEM Profile.

**Comment by Carnifrex** [comment]
Proposed fix: https://github.com/shinesolutions/puppet-aem-curator/pull/117

**Comment by cliffano** [comment]
@Carnifrex Thanks very much for the aem profile contribution.
