### ISSUE TITLE
Config dispatcher can't configure secure

### ISSUE THREAD

**Issue by Carnifrex** [shinesolutions/puppet-aem-curator#123]
In the files `config_dispatcher_author `and `config_dispatcher_publish` the variables `author_secure` and `publish_secure` are not passed to the `aem_resources/*_dispatcher_set_config`. The variabled are not used then.

**Comment by Carnifrex** [comment]
Proposed fix : #124

**Comment by cliffano** [comment]
@Carnifrex Thanks for this fix. Correct, those parameters should've been passed.
This has been released as part of version 2.1.0 .
