### ISSUE TITLE
Unable to specify debug port

### ISSUE THREAD

**Issue by henrykuijpers** [shinesolutions/puppet-aem-curator#132]
A Java program can have debugging set up, through the Java Debug Wire Protocol. This allows a developer to attach to a running program and step through code.

bstopp:puppet-aem has an option that allows an instance to have a debug port. Unfortunately, AEM Curator does not have this option, while it is still calling aem::instance.

We're now able to configure the debug port through the start options (which is there). But it is much sexier to configure this debug port and have it set up automatically. :)

**Comment by cliffano** [comment]
The PR has been merged and released as part of v2.7.0 .
