### ISSUE TITLE
deploy_artifact.sh not executed properly 

### ISSUE THREAD

**Issue by mbloch1986** [shinesolutions/puppet-aem-curator#14]
The Puppet manifest action_deploy_artifact.pp expects a variable `$::package_aem_id` which is missing in the bash script template `deploy-artifact.sh.epp` .

**Comment by mbloch1986** [comment]
If this is a variable which should be passed to the bash script, than we need to update the SSM Document as well. As the bash script is going to be executed from the stack-manager.

**Comment by mbloch1986** [comment]
Error msg: 

    "msg": {
        "instance_id": "i-0934e579ba3691301", 
        "log_file": "/Users/mbloch/Documents/projects/aem-stack-manager-messenger/logs/aem-stack-manager/stack-manager/SSMOutput/40c8f2ca-0049-4d33-9a1c-d199a3cec6b0/i-0934e579ba3691301/awsrunShellScript/runShellScript/stderr", 
        "log_output": "\u001b[1;33mWarning: /opt/shinesolutions/aem-aws-stack-provisioner/conf/hiera.yaml: Use of 'hiera.yaml' version 3 is deprecated. It should be converted to version 5\n   (in /opt/shinesolutions/aem-aws-stack-provisioner/conf/hiera.yaml)\u001b[0m\n\u001b[1;33mWarning: Undefined variable '::event'; \n   (file & line not available)\u001b[0m\n\u001b[1;33mWarning: Defining \"data_provider\": \"hiera\" in metadata.json is deprecated. A 'hiera.yaml' file should be used instead\n   (in /opt/shinesolutions/aem-aws-stack-provisioner/modules/aem_curator/metadata.json)\u001b[0m\n\u001b[1;33mWarning: Unknown variable: '::package_aem_id'. at /opt/shinesolutions/aem-aws-stack-provisioner/modules/aem_curator/manifests/action_deploy_artifact.pp:13:24\u001b[0m\n\u001b[1;31mError: /Stage[main]/Aem_curator::Action_deploy_artifact/Aem_package[Deploy package shinesolutions/aem-enable-crxde-0.0.1]: Could not evaluate: Unexpected response\nstatus code: 0\nheaders: \nbody: \u001b[0m\n\nfailed to run commands: exit status 6"

**Comment by cliffano** [comment]
Released in 0.9.13 .
