### ISSUE TITLE
Dispatcher flush agent should not be managed by publish reconfig

### ISSUE THREAD

**Issue by henrykuijpers** [shinesolutions/puppet-aem-curator#149]
See: https://github.com/shinesolutions/puppet-aem-curator/blob/417c3663be4a68ca1558ae3c7105c1445b1b8e06/manifests/config_publish.pp#L365

This registers a replication flush agent for the publish instance, at every reconfig. At that time, we do not know (yet) what the Dispatcher instance ID or hostname will be.

We're managing the replication agents in another location (just as we do for the author environment), so we believe this step should not be in place here.

I believe in the full setup, this is managed through the Orchestrator, which would mean that both Orchestrator and Curator are performing the same task. Hence, in my opinion, it could be removed.

**Comment by henrykuijpers** [comment]
@cliffano @mbloch1986 WDYT?

**Comment by mbloch1986** [comment]
hi @henrykuijpers 

no the Orchestrator and the Curator are not doing the same tasks here. You can find more information about what the orchestrator is doing during a scale up/down process in the documentation of the orchestrator https://github.com/shinesolutions/aem-orchestrator/blob/master/docs/scale-up-events.md.

Currently the Curator is the only one who is registering the Publish-Dispatcher Agents to the Publish instances. This could be a feature request in the future to let the orchestrator handle all agents activities but for now we need to do the publish-dispatcher agent tasks during the provisioning process of the publish instances.

As long as ther orchestrator is not managing all agent activities I think, as mentioned in #150 , the best solution would be to outsorce all agent activities to a own manifest file. This allows us to control this process on `aem-aws-stack-provisioner` level. 

It makes sure that you can use the curator in environments where no 1:1 mapping between the publish & publish-dispatcher exists and if still needed you can enable the agent creation.

Let me know what you think !

Cheers

**Comment by mbloch1986** [comment]
@henrykuijpers if you like you can test if the changes in this PR 

https://github.com/shinesolutions/puppet-aem-curator/pull/158

are fixing your issues?

**Comment by mbloch1986** [comment]
Solution implemented in release 3.2.0
