### ISSUE TITLE
not working commands

### ISSUE THREAD

**Issue by mbloch1986** [shinesolutions/puppet-aem-curator#15]
Ticket to doc not working commands

### Fixed with PR 
https://github.com/shinesolutions/puppet-aem-curator/pull/17 and https://github.com/shinesolutions/aem-aws-stack-provisioner/pull/57 

But haven't figured out the correct Syntax for parameter package-filter.

Exits with an error of an unacceptable JSONArray.

**Command:**

`./send-message.sh "michaelb-aem63" "ansible/inventory/group_vars/all.yaml" "ansible/inventory/group_vars/export-package.yaml" "component=author-primary package_group=shinesolutions package_name=aem-helloworld package_filter=[{"root":"/apps/helloworld","rules":[]},{"root":"/etc/designs/helloworld","rules":[]}]"`

**Error message:**

> Error: Could not set 'archived' on ensure: Could not modify package. A JSONArray text must start with \u0026#39;[\u0026#39; at character 1 of \u0026#34;{[{root:/apps/helloworld,rules:[]},{root:/etc/designs/helloworld,rules:[]}]}\u0026#34; at /opt/shinesolutions/aem-aws-stack-provisioner/manifests/export-backup.pp:21

after changing the encoding of the json payload in the Lambda function from

`encoded = json.loads(message['details']['package_filter'])`
to
`encoded = json.dumps(message['details']['package_filter'])`

I get following **error message:**

> Missing value. at character 7 of [{root:/apps/helloworld,rules:[]},{root:/etc/designs/helloworld,rules:[]}] at /opt/shinesolutions/aem-aws-stack-provisioner/manifests/export-backup.pp:2

**Comment by mbloch1986** [comment]
## export-packages

**command**
`
make export-packages stack_prefix=michaelb-aem63 topic_config_file=ansible/inventory/group_vars/all.yaml message_config_file=ansible/inventory/group_vars/export-packages.yaml component=author-primary descriptor_file=messenger/export-backup-descriptor.json`

**Error message**

> Feb 12 16:31:39 ip-172-31-35-58 amazon-ssm-agent: "standardError": "\u001b[1;31mError: Could not run: Could not find file manifests/download-descriptor.pp\u001b[0m\n\nfailed to run commands: exit status 1"

**Comment by mbloch1986** [comment]
## import-packages

**command**
`make import-package \
    stack_prefix=michaelb-aem63 \
    topic_config_file=ansible/inventory/group_vars/all.yaml \
    message_config_file=ansible/inventory/group_vars/import-package.yaml \
    component=author-primary \
    source_stack_prefix=cliffs3 \
    package_group=shinesolution \
    package_name=aem-helloworld \
    package_datestamp=2017-03
`

Error message

> 1Error: Execution of '/usr/bin/aws s3 cp s3://aem-stack-builder/backup/cliffs3/shinesolution/2017/-0/aem-helloworld-2017-03-author-primary.zip /tmp/aem-helloworld-2017-03-author-primary.zip_20180212-13444-129zeup' returned 1: fatal error: An error occurred (404) when calling the HeadObject operation: Key \"backup/cliffs3/shinesolution/2017/-0/aem-helloworld-2017-03-author-primary.zip\" does not exist

**Comment by mbloch1986** [comment]
## promote-author-standby-to-primary.sh

**command**
`make promote-author     stack_prefix=michaelb-aem63     topic_config_file=ansible/inventory/group_vars/all.yaml     message_config_file=ansible/inventory/group_vars/promote-author.yaml`

**Error message**
opt/shinesolutions/aem-tools/promote-author-standby-to-primary.sh: No such file or directory\n\nfailed to run commands: exit status 127"

**Reason:**
Missing creation block for the script in manifest config_aem_tools.pp

After adding the block, bash script is available and following error message appears:

**Error message**
Error: Function lookup() did not find a value for the name '::author_primary::enable_offline_compaction_cron'\u001b[0m\n\nfailed to run commands: exit status 1"

**Comment by mbloch1986** [comment]
### offline-snapshot


**Command:**

`./send-message.sh "michaelb-aem63" "ansible/inventory/group_vars/all.yaml" "ansible/inventory/group_vars/export-package.yaml" "component=author-primary package_group=shinesolutions package_name=aem-helloworld package_filter=[{"root":"/apps/helloworld","rules":[]},{"root":"/etc/designs/helloworld","rules":[]}]"`


**Error message:**

**Comment by mbloch1986** [comment]
### deploy-artifact
See issue:
https://github.com/shinesolutions/puppet-aem-curator/issues/14

**Comment by cliffano** [comment]
Released in 0.9.13 .
