### ISSUE TITLE
config_publish.pp & config_author_primary.pp remove all replication agents, including custom ones

### ISSUE THREAD

**Issue by henrykuijpers** [shinesolutions/puppet-aem-curator#150]
When executing config_publish / config_author_primary, as part of all the actions, all replication agents on the instance are removed.

For us, this is a problem: We're dynamically registering replication agents whenever we need to scale up a Dispatcher. I.e. it could be that we have 3 Dispatcher flush agents, or just 1, or even 10, for a specific AEM instance.

Removing all replication agents from the instance, means that we also remove the dynamically registered replication agents. We're unable to register those replication agents again later on, since we rely on AWS instance IDs & the host names that are known within AWS. From our scripting we are not aware of all Dispatchers that exist.

Do you see any possible fix for this?

**Comment by mbloch1986** [comment]
Hi @henrykuijpers,

this is a fair point. 

The step to remove all agents from the author and publish instance may specific to our environment setup. In our case if you use a backup/snapshot to create the Author or Publish instance than this AEM instance contains the configured agents which were part of the snapshot. 

So to make sure there are no outdated agents configured we are always removing them and as you already mentioned in #149 we are configuring all required agents later. 

One possible fix could be to outsorce all agent activities to a own manifest in `puppet-aem-curator` with a flag which is disabled per default. This way we can pass the enable flag on the `aem-aws-stack-provisioner` lvl, which makes more sense for us as well, and we can support cases like yours.

What do you think of it ?

**Comment by mbloch1986** [comment]
Solution implemented in version 3.2.0
