### ISSUE TITLE
reconfig_aem.pp restarts AEM even if it is not necessary to do so

### ISSUE THREAD

**Issue by henrykuijpers** [shinesolutions/puppet-aem-curator#151]
See: https://github.com/shinesolutions/puppet-aem-curator/blob/417c3663be4a68ca1558ae3c7105c1445b1b8e06/manifests/reconfig_aem.pp#L180

This means the AEM author/publish service will be restarted everytime a reconfig is called, even if it does not involve any changes that require an AEM restart.

**Comment by mbloch1986** [comment]
@henrykuijpers I agree with you it shouldn't be required for AEM to restart. We are doing some offline-tasks during the reconfiguration, but these offline-tasks can be done before AEM starts I've alrady updated the reconfiguration logic with this PR: 

https://github.com/shinesolutions/puppet-aem-curator/pull/144

We are planning to merge this PR soonish. 

In the future the reconfiguration is done in two steps, a pre part and the main part. The pre part does all action which needs to be done while AEM is not started and the main part which is processed after AEM was started. 

One new feature we added to the reconfiguration is the reset of the files `bin/start` & `bin/start-env`.

**Comment by mbloch1986** [comment]
Hi @henrykuijpers this change is now included in release version 3.0.0. Since this is fixed I'm going to close this ticket.
