### ISSUE TITLE
Installation Migration is forced when enabling aem reconfig

### ISSUE THREAD

**Issue by Carnifrex** [shinesolutions/puppet-aem-curator#167]
When reconfiguring AEM we put the "enable_aem_reconfiguration" on true, but this will also set the "enable_aem_installation_migration" on true. The migration should get a separate variable as the migration is not done on every reconfiguration.

https://github.com/shinesolutions/puppet-aem-curator/blob/master/manifests/config_publish.pp#L121

https://github.com/shinesolutions/puppet-aem-curator/blob/master/manifests/config_author_primary.pp#L127

**Comment by Carnifrex** [comment]
Proposed fix: https://github.com/shinesolutions/puppet-aem-curator/pull/168

**Comment by mbloch1986** [comment]
@Carnifrex Thanks for the tiicket and the PR.

Before we can merge you're PR we need to update the `aem-aws-stack-provisioner` so we can keep the backward compatibility. 

But yes I do agree with you that it might be the best to have a seperated variable to enable the aem installation migration.
