### ISSUE TITLE
Add notify AEM when configuring the JVM_OTPS in config_publish

### ISSUE THREAD

**Issue by Carnifrex** [shinesolutions/puppet-aem-curator#173]
In config_publish changing the jvm_opt will not notify the aem service:
https://github.com/shinesolutions/puppet-aem-curator/blob/master/manifests/config_publish.pp#L180

We should add notify => Service['aem-publish'] like its done in the config_author_primary: 
https://github.com/shinesolutions/puppet-aem-curator/blob/master/manifests/config_author_primary.pp#L186

**Comment by mbloch1986** [comment]
@Carnifrex Changes are included in release 3.11.0. Therefor I'll close this ticket. please re-open it if it is still happening for you.
