### ISSUE TITLE
Move to Adobe's Dispatcher module.

### ISSUE THREAD

**Issue by bstopp** [shinesolutions/puppet-aem-curator#174]
Team - This is a heads-up that I will be deprecating the Dispatcher support in my Puppet module. I have published a new, dispatcher specific module [here](https://github.com/adobe/puppet-dispatcher). I am finalizing the documentation before I cut a 1.0 release, however no functionality/APIs should be changing. 

I'd love to see your system updated to reference this and provide feedback/issues should I have missed something.

**Comment by mbloch1986** [comment]
@bstopp Thank you for the notice, really appreciated.

I guess nothing really changed codewise ? 

We'll test it and keep you updated.

**Comment by bstopp** [comment]
Actually no - it's pretty significantly overhauled to use more structured input.

I also made some improvements for auto-loading farm information from hiera when you configure the dispatcher class. But I am still working on the documentation for those parts.

**Comment by mbloch1986** [comment]
> [...]
> I also made some improvements for auto-loading farm information from hiera when you configure the dispatcher class. But I am still working on the documentation for those parts.
> 
> On the plus side: Both regex and globbing is available wherever it they are both supported.

This looks very interesting, you basically maintain your dispatcher configuration as a dictionary and pass it to the dispatcher class ? 

I integrated the new dispatcher module and the tests were successful so far. I took the opportunity to also cleanup our dispatcher manifest a little bit.

Do you already know when you are going to release the new dispatcher module ?

**Comment by mbloch1986** [comment]
Included in release 3.18.0
