### ISSUE TITLE
SegmentNodeStoreService configuration gets deleted when configuring primary author

### ISSUE THREAD

**Issue by henrykuijpers** [shinesolutions/puppet-aem-curator#200]
We have a primary author that has a configuration for a FileDataStore, which means we need to put a configuration for SegmentNodeStoreService as well (customBlobStore=true).

When running a config-step, we noticed that that configuration (in the install-folder) gets deleted! We tracked it down to the principle that is applied when promoting a standby author to a primary author. The result of that is that the SegmentNodeStoreService configuration (which is assumed there to have been created because of the fact that it was a standby author, which is not true in this case) gets deleted if it exists.

That check is therefore not correct: We have the configuration there only to indicate that we have a customBlobStore (because we're using an S3 DataStore).

**Comment by henrykuijpers** [comment]
Maybe the check can be improved, or the SegmentNodeStoreService configuration can be written with a marker that indicates that configuration was put there because of the standby/primary concept? That marker could be checked then, causing it to leave our config there.

Or it could actually leave the SegmentNodeStoreService config there, but just remove the standby property?

WDYT, @mbloch1986 / @cliffano ?

**Comment by mbloch1986** [comment]
@henrykuijpers can you please explain in which scenario this is happening ? Does it happen when you promote an author-standby to an author-primary ot is this happenning when running the `config_author_primary` in puppet-aem-curator ?

**Comment by henrykuijpers** [comment]
It's indeed when running config_author_primary. Our SNSS configuration contains customBlobStore=true and it's very important that that property stays. :P especially since AEM is always restarted due to the JMX remote bug.

**Comment by mbloch1986** [comment]
@henrykuijpers 

I got your point.... a few questions... how many custom configurations do you have configured in your SegmentNodeStoreService config file ? Also what's the AEM Version you are using ?

**Comment by henrykuijpers** [comment]
We're using the crx3tar-nofds runmode. Is it then still default true? We're using that runmode because we're using an S3 datastore setup. 

We're on AEM 6.5.2 (and going to upgrade to aem 6.5.4).

**Comment by mbloch1986** [comment]
Apart from what we are currently configuring in the [SegmentNodeStoreService.config](https://github.com/shinesolutions/puppet-aem-resources/blob/master/files/SegmentNodeStoreService.config) config file are there any other configuration parameters you are adding to it ?

**Comment by mbloch1986** [comment]
@henrykuijpers the latest version of puppet-aem-curator 3.12.0 include the change that it sets the config file for SegmentNodeStoreService on the author-primary with the setting `customBlobStore=true` for AEM 6.3+ and `customBlobStore=flase` for AEM 6.2.

**Comment by mbloch1986** [comment]
fix with puppet-aem-curator version 3.12.0
