### ISSUE TITLE
AEM SSL by default, Adobe healthcheck still fails?

### ISSUE THREAD

**Issue by henrykuijpers** [shinesolutions/puppet-aem-curator#218]
We've configured AEM to run on SSL through curator, however, the healthcheck from Adobe Security still fails. It complains about the absence of a Granite SSL Connector.

**Comment by mbloch1986** [comment]
Do you have the output of the system health check ? You can get the outpur of the Healthchck with the following command on the author-primary:

```
curl http://localhost:4502/system/health?tags=shallow
curl http://localhost:4502/system/health?tags=deep
```

**Comment by mbloch1986** [comment]
@henrykuijpers  I'll close this one, since we can't reproduce the error and puppet-aem-curtor version `3.15.0` has the support of enabling SSL via Granite(AEM SSL by default).
