### ISSUE TITLE
Add 6.5 SP9 AEM profile

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/puppet-aem-curator#235]
**Is your feature request related to a problem? Please describe.**
Users would like to use AEM 6.5 SP9.

**Describe the solution you'd like**
Add `aem65_sp9` AEM profile to puppet-aem-curator to be used in upstream AOC libraries.

**Comment by mbloch1986** [comment]
Added AEM 6.5 SP9 to master

**Comment by mbloch1986** [comment]
Included in version 3.20.0
