### ISSUE TITLE
Move stack prefix and component details to dimension

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/puppet-aem-curator#25]
Collectd CW metric currently include stack prefix and component in its host value.
The intention is to provide more environment info to the metric.

However, this causes the sync delay alarm to be unable to recognise the associated metric on EC2 console. This reduces visibility for user's operations and support team when checking the alarms for the instances associated to a given stack prefix.

We need to:
1. Set the metric host value back to the instance ID, in order to show alarm status on EC2 console
2. Set fixed dimension that shows stack prefix and component info, in order to assist users when trying to identify the metrics for a given environment

**Comment by ovlords** [comment]
Need to set the values for /opt/collectd-cloudwatch/src/cloudwatch/config/plugin.conf to the following:


push_constant = True
constant_dimension_value = "prefix-value"

**Comment by cliffano** [comment]
CloudWatch config should be migrated away from curator as part of https://github.com/shinesolutions/puppet-aem-curator/issues/38 .

**Comment by cliffano** [comment]
Done. Included in 0.9.21 .
