### ISSUE TITLE
Introduce scheduled events config

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/puppet-aem-curator#33]
Full-Set architecture includes scheduled events (e.g. nightly offline snapshots and weekly offline compaction) via Orchestrator component.

Consolidated architecture currently doesn't have these scheduled events. Those events should be extracted from Orchestrator component and live as a config in aem-curator, so that both Orchestrator and AuthorPublishDispatcher components include those scheduled events.

**Comment by mbloch1986** [comment]
Scheduled events are AWS specific and needs to be configured on the stack provisioner level.
