### ISSUE TITLE
Pass configuration to action manifests' InSpec tests

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/puppet-aem-curator#35]
Action manifests InSpec tests are currently using default ruby_aem config.
It should use the config file that's provisioned on the instance.

In the case of an instance with multiple AEMs, it needs to handle multiple configurations.

**Comment by mbloch1986** [comment]
Done.

**Comment by mbloch1986** [comment]
Released with AEM AWS Stack Provisioner version 2.4.10
