### ISSUE TITLE
Upgrade Inspec version 

### ISSUE THREAD

**Issue by mbloch1986** [shinesolutions/puppet-aem-curator#60]
Since Inspec version 2.2.101  the way inspec handles vendoring changed. 

Before 2.2.101 the inspec-profiles were just downloaded to the vendor directory now they get downloaded and extracted. See also 
https://github.com/inspec/inspec/pull/3286 
for more detail information check
https://github.com/inspec/inspec/blame/master/lib/inspec/profile_vendor.rb#L59.

This brakes the current ```make deps``` make target to work. We need to change the behavior of the make target.

**Comment by cliffano** [comment]
Done. To be included in v1.2.1 and v0.11.1 .
