### ISSUE TITLE
 Parameterise wait until aem is healthy while configuring AEM

### ISSUE THREAD

**Issue by mbloch1986** [shinesolutions/puppet-aem-curator#76]
While configuring Publish and Author Primary we need to pass the parameters

```
login_ready_max_tries
login_ready_base_sleep_seconds
login_ready_max_sleep_seconds
```

to all AEM Healthcheck.

AEM64 with content may take a bit longer to configure.

**Comment by cliffano** [comment]
Done. To be included in 1.2.4 .
